CREATE TABLE IF NOT EXISTS livros (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    genero VARCHAR(150) NOT NULL,
    qtd_paginas INT NOT NULL,
    ano_publicado INT NOT NULL
);

INSERT INTO livros (titulo, autor, genero, qtd_paginas, ano_publicado)
VALUES ('Entendendo Algoritmos', 'Aditya', 'Computação e Informática', 264, '2017');